"""Review,Cloth table

Revision ID: f5e1e5a46dc2
Revises: bed0723c5e1d
Create Date: 2026-09-05 08:26:29.533323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'f5e1e5a46dc2'
down_revision: Union[str, Sequence[str], None] = 'bed0723c5e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_user_id'), 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_user_id', 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_user_id', 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_user_id'), 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
